{
  "5f89ffe37f2669f39b24d1101044b17b" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 0,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "69478fb4c38310d1",
      "status" : "passed",
      "time" : {
        "start" : 1595042921942,
        "stop" : 1595042921946,
        "duration" : 4
      }
    } ]
  },
  "498cfa9162dedf00332858a41ec05b97" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 0,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "1119fa08cbd9b586",
      "status" : "passed",
      "time" : {
        "start" : 1595042921985,
        "stop" : 1595042921986,
        "duration" : 1
      }
    } ]
  },
  "8c8070be64bd4760a81772b501bf9b63" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 0,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "c869fe3f74f82742",
      "status" : "passed",
      "time" : {
        "start" : 1595042921947,
        "stop" : 1595042921948,
        "duration" : 1
      }
    } ]
  },
  "5f1732f73d8ac4858a54c85c85bff1d2" : {
    "statistic" : {
      "failed" : 1,
      "broken" : 0,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "dddbc799adb4ece6",
      "status" : "failed",
      "statusDetails" : "AssertionError: assert 2 != 2",
      "time" : {
        "start" : 1595042921950,
        "stop" : 1595042921983,
        "duration" : 33
      }
    } ]
  },
  "3f11b6e01d73ae0dd69445d8f2405c9c" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "64232928c9e06cfa",
      "status" : "broken",
      "statusDetails" : "MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B0EB7A1F08>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1595042921988,
        "stop" : 1595042931330,
        "duration" : 9342
      }
    } ]
  }
}